# Generated by Django 6.0.4 on 2026-04-18 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AthleteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('height', models.DecimalField(decimal_places=2, help_text='Height in cm', max_digits=5)),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight in kg', max_digits=5)),
                ('body_type', models.CharField(max_length=100)),
                ('injuries', models.TextField(blank=True, null=True)),
                ('strengths', models.TextField(blank=True, null=True)),
                ('weaknesses', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue_per_month', models.DecimalField(decimal_places=2, max_digits=12)),
                ('athlete_numbers', models.PositiveIntegerField()),
                ('conversion_rate', models.DecimalField(decimal_places=2, help_text='Percentage of leads becoming members', max_digits=5)),
                ('total_income', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expected_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Basketball',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
                ('vertical_jump', models.DecimalField(decimal_places=2, help_text='Vertical leap in inches', max_digits=5)),
                ('attendance', models.DecimalField(decimal_places=2, help_text='Attendance percentage', max_digits=5)),
                ('shooting_stats', models.JSONField(blank=True, default=dict)),
                ('performance_metrics', models.JSONField(blank=True, default=dict)),
                ('current_game_high', models.PositiveIntegerField(help_text='Highest points in a single game')),
                ('expected_performance', models.JSONField(blank=True, default=dict)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basketball_records', to='athletes.athleteinfo')),
            ],
        ),
        migrations.CreateModel(
            name='CrossFit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=100)),
                ('attendance', models.DecimalField(decimal_places=2, help_text='Attendance percentage', max_digits=5)),
                ('strength_maxes', models.JSONField(blank=True, default=dict)),
                ('benchmark_wods', models.JSONField(blank=True, default=dict)),
                ('gymnastics_proficiency', models.JSONField(blank=True, default=dict)),
                ('expected_pr_projection', models.JSONField(blank=True, default=dict)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crossfit_records', to='athletes.athleteinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Fitness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_plan', models.TextField()),
                ('workout_type', models.CharField(max_length=100)),
                ('attendance', models.DecimalField(decimal_places=2, help_text='Attendance percentage', max_digits=5)),
                ('sessions_per_week', models.PositiveIntegerField()),
                ('previous_fitness_tests', models.JSONField(blank=True, default=dict)),
                ('current_fitness_tests', models.JSONField(blank=True, default=dict)),
                ('expected_fitness_results', models.JSONField(blank=True, default=dict)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('nutrition_plan', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('athlete', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fitness_profile', to='athletes.athleteinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Football',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
                ('attendance', models.DecimalField(decimal_places=2, help_text='Attendance percentage', max_digits=5)),
                ('technical_stats', models.JSONField(blank=True, default=dict)),
                ('physical_data', models.JSONField(blank=True, default=dict)),
                ('match_impact', models.JSONField(blank=True, default=dict)),
                ('expected_growth_trajectory', models.JSONField(blank=True, default=dict)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='football_records', to='athletes.athleteinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Swimming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stroke', models.CharField(max_length=100)),
                ('events', models.CharField(max_length=255)),
                ('attendance', models.DecimalField(decimal_places=2, help_text='Attendance percentage', max_digits=5)),
                ('current_record', models.DurationField()),
                ('previous_record', models.DurationField(blank=True, null=True)),
                ('expected_record', models.DurationField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swimming_records', to='athletes.athleteinfo')),
            ],
        ),
    ]
