# Generated by Django 6.0.4 on 2026-04-18 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitness',
            name='inbody_file',
            field=models.FileField(blank=True, null=True, upload_to='inbody/'),
        ),
    ]
