# Generated by Django 6.0.4 on 2026-04-18 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0002_fitness_inbody_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitness',
            name='fitness_goal',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='swimming',
            name='swimming_goal',
            field=models.TextField(blank=True, null=True),
        ),
    ]
