# Generated by Django 6.0.4 on 2026-04-18 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0003_fitness_fitness_goal_swimming_swimming_goal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basketball',
            name='attendance',
        ),
        migrations.RemoveField(
            model_name='crossfit',
            name='attendance',
        ),
        migrations.RemoveField(
            model_name='fitness',
            name='attendance',
        ),
        migrations.RemoveField(
            model_name='football',
            name='attendance',
        ),
        migrations.RemoveField(
            model_name='swimming',
            name='attendance',
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('attended', models.BooleanField(default=False)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='athletes.athleteinfo')),
            ],
            options={
                'unique_together': {('athlete', 'date')},
            },
        ),
    ]
