# Generated by Django 6.0.4 on 2026-04-18 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0004_remove_basketball_attendance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='coach_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='performance_rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Rating from 1 to 10', null=True),
        ),
    ]
