# Generated by Django 6.0.4 on 2026-04-24 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0009_athleteinfo_subscription_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='athleteinfo',
            name='subscription_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Fee in EGP', max_digits=10),
        ),
    ]
