# Generated by Django 6.0.4 on 2026-04-25 14:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0010_athleteinfo_subscription_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athleteinfo',
            name='injuries',
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='fatigue_score',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Fatigue Score (1-10, 10 is max fatigue)', null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='hrv',
            field=models.PositiveIntegerField(blank=True, help_text='Heart Rate Variability (ms)', null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='muscle_soreness',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Muscle Soreness (1-10, 10 is max soreness)', null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='resting_heart_rate',
            field=models.PositiveIntegerField(blank=True, help_text='Resting Heart Rate (bpm)', null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='sleep_hours',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Sleep Hours', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='athleteinfo',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
        migrations.CreateModel(
            name='InjuryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Current Injury Status (Yes/No)')),
                ('injury_type', models.CharField(max_length=255)),
                ('severity', models.CharField(choices=[('Mild', 'Mild'), ('Moderate', 'Moderate'), ('Severe', 'Severe')], max_length=50)),
                ('start_date', models.DateField(default=django.utils.timezone.localdate)),
                ('expected_recovery_time', models.CharField(blank=True, help_text='e.g. 2 weeks', max_length=100, null=True)),
                ('estimated_return_date', models.DateField(blank=True, null=True)),
                ('medical_notes', models.TextField(blank=True, null=True)),
                ('cleared_to_train', models.BooleanField(default=False)),
                ('cleared_by', models.CharField(blank=True, help_text='Coach, Doctor, Physio', max_length=100, null=True)),
                ('returned_before_recovery', models.BooleanField(default=False)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='injury_records', to='athletes.athleteinfo')),
            ],
        ),
    ]
