# Generated by Django 6.0.4 on 2026-04-26 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0011_remove_athleteinfo_injuries_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='workout_completed',
            field=models.BooleanField(default=False, help_text='Did the athlete complete their assigned workout for this session?'),
        ),
    ]
