# Generated by Django 6.0.4 on 2026-04-29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0012_attendancerecord_workout_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='athleteinfo',
            name='academy_since',
            field=models.DateField(default=django.utils.timezone.localdate, editable=False),
        ),
        migrations.AddField(
            model_name='athleteinfo',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
