# Generated by Django 6.0.4 on 2026-05-02 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0013_athleteinfo_date_of_birth_and_academy_since'),
    ]

    operations = [
        migrations.AddField(
            model_name='swimming',
            name='lap_distance',
            field=models.CharField(blank=True, help_text='e.g. 50m, 25m, 12.5m', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='swimming',
            name='splits_data',
            field=models.JSONField(blank=True, default=list, help_text='List of objects with lap_number, previous, current, expected'),
        ),
        migrations.AddField(
            model_name='swimming',
            name='total_laps',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
