# Generated by Django 6.0.4 on 2026-05-03 00:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0014_swimming_lap_distance_swimming_splits_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='injuryrecord',
            name='rehab_phase',
            field=models.CharField(choices=[('Acute', 'Acute Phase'), ('Mobility', 'Mobility & ROM'), ('Load', 'Load Bearing'), ('Sport', 'Sport Specific'), ('Cleared', 'Cleared for Play')], default='Acute', max_length=50),
        ),
        migrations.CreateModel(
            name='PainLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('body_part', models.CharField(max_length=100)),
                ('pain_level', models.PositiveSmallIntegerField(help_text='Pain Level (1-10)')),
                ('pain_type', models.CharField(help_text='e.g. Sharp, Dull, Aching', max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pain_logs', to='athletes.athleteinfo')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
